#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c5e9e788-940d-417f-ba3e-b1b01af648bb/call-hello/execution
echo 'Hello NLFDEIVAZM!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c5e9e788-940d-417f-ba3e-b1b01af648bb/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c5e9e788-940d-417f-ba3e-b1b01af648bb/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c5e9e788-940d-417f-ba3e-b1b01af648bb/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c5e9e788-940d-417f-ba3e-b1b01af648bb/call-hello/execution/rc
