#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/63d4d33a-8694-49bd-913c-8366a67be616/call-hello/execution
echo 'Hello SDNZPVAIOR!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/63d4d33a-8694-49bd-913c-8366a67be616/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/63d4d33a-8694-49bd-913c-8366a67be616/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/63d4d33a-8694-49bd-913c-8366a67be616/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/63d4d33a-8694-49bd-913c-8366a67be616/call-hello/execution/rc
