#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0379c7fe-de0d-46a9-8f75-f1eb9e1146fb/call-hello/execution
echo 'Hello ELWBDIYVKM!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0379c7fe-de0d-46a9-8f75-f1eb9e1146fb/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0379c7fe-de0d-46a9-8f75-f1eb9e1146fb/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0379c7fe-de0d-46a9-8f75-f1eb9e1146fb/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0379c7fe-de0d-46a9-8f75-f1eb9e1146fb/call-hello/execution/rc
