#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/eea5fdb3-2cdf-43e6-9709-eeccd40a2783/call-hello/execution
echo 'Hello UFKDWEHVXL!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/eea5fdb3-2cdf-43e6-9709-eeccd40a2783/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/eea5fdb3-2cdf-43e6-9709-eeccd40a2783/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/eea5fdb3-2cdf-43e6-9709-eeccd40a2783/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/eea5fdb3-2cdf-43e6-9709-eeccd40a2783/call-hello/execution/rc
