#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/133bf832-d8f4-45d5-89e2-53241877611c/call-hello/execution
echo 'Hello SFXLPKQAJT!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/133bf832-d8f4-45d5-89e2-53241877611c/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/133bf832-d8f4-45d5-89e2-53241877611c/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/133bf832-d8f4-45d5-89e2-53241877611c/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/133bf832-d8f4-45d5-89e2-53241877611c/call-hello/execution/rc
