#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ad6d316f-4197-4c2d-a325-c9f06ade5256/call-hello/execution
echo 'Hello SUXIZWNMAP!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ad6d316f-4197-4c2d-a325-c9f06ade5256/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ad6d316f-4197-4c2d-a325-c9f06ade5256/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ad6d316f-4197-4c2d-a325-c9f06ade5256/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ad6d316f-4197-4c2d-a325-c9f06ade5256/call-hello/execution/rc
