#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a91c1816-05fd-4dce-86cf-82d041dff8a3/call-hello/execution
echo 'Hello DUHIFXWLKY!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a91c1816-05fd-4dce-86cf-82d041dff8a3/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a91c1816-05fd-4dce-86cf-82d041dff8a3/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a91c1816-05fd-4dce-86cf-82d041dff8a3/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a91c1816-05fd-4dce-86cf-82d041dff8a3/call-hello/execution/rc
