#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/85ec7565-92cc-4cc2-bb87-543a88a689a3/call-hello/execution
echo 'Hello FTYRSABWLH!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/85ec7565-92cc-4cc2-bb87-543a88a689a3/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/85ec7565-92cc-4cc2-bb87-543a88a689a3/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/85ec7565-92cc-4cc2-bb87-543a88a689a3/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/85ec7565-92cc-4cc2-bb87-543a88a689a3/call-hello/execution/rc
