#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/2c51015a-4261-4401-b512-00267ca02adb/call-hello/execution
echo 'Hello BTWZPSODUG!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/2c51015a-4261-4401-b512-00267ca02adb/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/2c51015a-4261-4401-b512-00267ca02adb/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/2c51015a-4261-4401-b512-00267ca02adb/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/2c51015a-4261-4401-b512-00267ca02adb/call-hello/execution/rc
