#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/92a47ceb-aafe-4446-a8bc-e6197d616ad6/call-hello/execution
echo 'Hello LTRBJWEYAV!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/92a47ceb-aafe-4446-a8bc-e6197d616ad6/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/92a47ceb-aafe-4446-a8bc-e6197d616ad6/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/92a47ceb-aafe-4446-a8bc-e6197d616ad6/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/92a47ceb-aafe-4446-a8bc-e6197d616ad6/call-hello/execution/rc
