#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/d2d8edca-cc34-4ae8-8dd3-fb1813fb553d/call-hello/execution
echo 'Hello PJFLORSUWN!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/d2d8edca-cc34-4ae8-8dd3-fb1813fb553d/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/d2d8edca-cc34-4ae8-8dd3-fb1813fb553d/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/d2d8edca-cc34-4ae8-8dd3-fb1813fb553d/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/d2d8edca-cc34-4ae8-8dd3-fb1813fb553d/call-hello/execution/rc
