---
author: 'Sean Davis'
title: 'Introduction to the cRomwell package'
date: '`r Sys.Date()`'
output: html_document
---

```{r}
cwd = getwd()
tmpdir = tempdir()
setwd(tmpdir)
httr::GET('https://github.com/broadinstitute/cromwell/releases/download/0.22/cromwell-0.22.jar',
          httr::write_disk('cromwell.jar'))
system('java -jar cromwell.jar server > cromwell.log 2>&1 &')
# let server start up
Sys.sleep(20)
system('ps aux | grep cromwell')
setwd(cwd)
```

```{r}
hello_wdl = "task hello {
  String name

  command {
    echo 'Hello ${name}!'
  }
  output {
    File response = stdout()
  }
}

workflow test {
  call hello
}"
```

```{r}
options(cromwell_base = 'http://localhost:8000')
randomStrings = sapply(1:10,function(r) {paste(sample(LETTERS,10),collapse="")})
wdlInputs = data.frame(test.hello.name=randomStrings)
z = cromwellBatch(wdlSource = hello_wdl,workflowInputs=toJSON(wdlInputs))
Sys.sleep(20)
cromwellQuery()
```

```{r}
#read from github or other URL
hello_remote_wdl = content(GET("https://raw.githubusercontent.com/DockstoreTestUser/dockstore-whalesay/master/Dockstore.wdl"),'text')
if(require(babyNames))
    wdlInputs = data.frame(test.hello.name=sample(babynames$name,10))
z = cromwellBatch(wdlSource = hello_remote_wdl,workflowInputs=toJSON(wdlInputs))
Sys.sleep(20)
cromwellQuery()
```


```{r}
# messy!
system('pgrep java | xargs -I {} kill -9 {}')
unlink(file.path(tmpdir,'cromwell*'),recursive=TRUE)
```
