#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/037958ad-8b2b-4404-9c0e-53c5bc89ae9f/call-hello/execution
echo 'Hello GICHEFRMBL!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/037958ad-8b2b-4404-9c0e-53c5bc89ae9f/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/037958ad-8b2b-4404-9c0e-53c5bc89ae9f/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/037958ad-8b2b-4404-9c0e-53c5bc89ae9f/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/037958ad-8b2b-4404-9c0e-53c5bc89ae9f/call-hello/execution/rc
