#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/610f2407-b8e6-4511-a8cb-d167d2af2443/call-hello/execution
echo 'Hello POCRZQKFJD!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/610f2407-b8e6-4511-a8cb-d167d2af2443/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/610f2407-b8e6-4511-a8cb-d167d2af2443/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/610f2407-b8e6-4511-a8cb-d167d2af2443/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/610f2407-b8e6-4511-a8cb-d167d2af2443/call-hello/execution/rc
