#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5bf02c39-cae3-4518-b0a4-1fb87e374d6a/call-hello/execution
echo 'Hello FEXNDGIPRZ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5bf02c39-cae3-4518-b0a4-1fb87e374d6a/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5bf02c39-cae3-4518-b0a4-1fb87e374d6a/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5bf02c39-cae3-4518-b0a4-1fb87e374d6a/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5bf02c39-cae3-4518-b0a4-1fb87e374d6a/call-hello/execution/rc
