#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/534127a9-e6ca-4ec4-be0f-6a2aa265674b/call-hello/execution
echo 'Hello YLDUJQVEXC!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/534127a9-e6ca-4ec4-be0f-6a2aa265674b/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/534127a9-e6ca-4ec4-be0f-6a2aa265674b/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/534127a9-e6ca-4ec4-be0f-6a2aa265674b/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/534127a9-e6ca-4ec4-be0f-6a2aa265674b/call-hello/execution/rc
