#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/982ea60d-c5d8-4763-b3b2-9415e0f77e19/call-hello/execution
echo 'Hello HGYCVWINFX!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/982ea60d-c5d8-4763-b3b2-9415e0f77e19/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/982ea60d-c5d8-4763-b3b2-9415e0f77e19/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/982ea60d-c5d8-4763-b3b2-9415e0f77e19/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/982ea60d-c5d8-4763-b3b2-9415e0f77e19/call-hello/execution/rc
