#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/256ae6d5-cd5b-47d8-a964-7cb854596499/call-hello/execution
echo 'Hello GSHBZTRJKD!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/256ae6d5-cd5b-47d8-a964-7cb854596499/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/256ae6d5-cd5b-47d8-a964-7cb854596499/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/256ae6d5-cd5b-47d8-a964-7cb854596499/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/256ae6d5-cd5b-47d8-a964-7cb854596499/call-hello/execution/rc
