#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e9a95c14-9a09-4a87-a477-a3476ac96a36/call-hello/execution
echo 'Hello XKVEQDJCLF!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e9a95c14-9a09-4a87-a477-a3476ac96a36/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e9a95c14-9a09-4a87-a477-a3476ac96a36/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e9a95c14-9a09-4a87-a477-a3476ac96a36/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e9a95c14-9a09-4a87-a477-a3476ac96a36/call-hello/execution/rc
