#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9f2bb16-bee4-46ca-b2f8-ede8cfbb55c8/call-hello/execution
echo 'Hello MRGNIZVEWH!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9f2bb16-bee4-46ca-b2f8-ede8cfbb55c8/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9f2bb16-bee4-46ca-b2f8-ede8cfbb55c8/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9f2bb16-bee4-46ca-b2f8-ede8cfbb55c8/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9f2bb16-bee4-46ca-b2f8-ede8cfbb55c8/call-hello/execution/rc
