#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1c79724a-c6f2-4b03-b71e-88b8d6dcb61a/call-hello/execution
echo 'Hello RAXOYENIGL!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1c79724a-c6f2-4b03-b71e-88b8d6dcb61a/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1c79724a-c6f2-4b03-b71e-88b8d6dcb61a/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1c79724a-c6f2-4b03-b71e-88b8d6dcb61a/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1c79724a-c6f2-4b03-b71e-88b8d6dcb61a/call-hello/execution/rc
