#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/288c2aa3-19f7-47a7-8ea4-12d1169a3fe6/call-hello/execution
echo 'Hello ALYWORSBQJ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/288c2aa3-19f7-47a7-8ea4-12d1169a3fe6/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/288c2aa3-19f7-47a7-8ea4-12d1169a3fe6/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/288c2aa3-19f7-47a7-8ea4-12d1169a3fe6/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/288c2aa3-19f7-47a7-8ea4-12d1169a3fe6/call-hello/execution/rc
