#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0adcb69b-a5dc-4726-8e8a-80f6f116458c/call-hello/execution
echo 'Hello ETMKYPUQXS!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0adcb69b-a5dc-4726-8e8a-80f6f116458c/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0adcb69b-a5dc-4726-8e8a-80f6f116458c/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0adcb69b-a5dc-4726-8e8a-80f6f116458c/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0adcb69b-a5dc-4726-8e8a-80f6f116458c/call-hello/execution/rc
