#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/104dbc3f-5c4c-4eb9-9b95-87ff97f20972/call-hello/execution
echo 'Hello GVLMOZFTPW!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/104dbc3f-5c4c-4eb9-9b95-87ff97f20972/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/104dbc3f-5c4c-4eb9-9b95-87ff97f20972/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/104dbc3f-5c4c-4eb9-9b95-87ff97f20972/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/104dbc3f-5c4c-4eb9-9b95-87ff97f20972/call-hello/execution/rc
