#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/49fde7a3-7ba4-423b-b020-aaff2c79d877/call-hello/execution
echo 'Hello MHAZRNBUWS!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/49fde7a3-7ba4-423b-b020-aaff2c79d877/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/49fde7a3-7ba4-423b-b020-aaff2c79d877/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/49fde7a3-7ba4-423b-b020-aaff2c79d877/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/49fde7a3-7ba4-423b-b020-aaff2c79d877/call-hello/execution/rc
