#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/838f35b4-8cdc-4977-ae4c-7c4869d888b3/call-hello/execution
echo 'Hello MFHQYCVDJB!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/838f35b4-8cdc-4977-ae4c-7c4869d888b3/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/838f35b4-8cdc-4977-ae4c-7c4869d888b3/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/838f35b4-8cdc-4977-ae4c-7c4869d888b3/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/838f35b4-8cdc-4977-ae4c-7c4869d888b3/call-hello/execution/rc
