#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5403503b-63b8-406a-9ba0-2203678d4e26/call-hello/execution
echo 'Hello WRISHPZXDA!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5403503b-63b8-406a-9ba0-2203678d4e26/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5403503b-63b8-406a-9ba0-2203678d4e26/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5403503b-63b8-406a-9ba0-2203678d4e26/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5403503b-63b8-406a-9ba0-2203678d4e26/call-hello/execution/rc
