#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/da89e2b8-303b-4c9b-b15d-a7f5286fc681/call-hello/execution
echo 'Hello QZOWDFKCXU!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/da89e2b8-303b-4c9b-b15d-a7f5286fc681/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/da89e2b8-303b-4c9b-b15d-a7f5286fc681/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/da89e2b8-303b-4c9b-b15d-a7f5286fc681/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/da89e2b8-303b-4c9b-b15d-a7f5286fc681/call-hello/execution/rc
