#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/72dcdb89-42cd-4caa-9e17-bb4d6596bd41/call-hello/execution
echo 'Hello YKDBTMOJFZ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/72dcdb89-42cd-4caa-9e17-bb4d6596bd41/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/72dcdb89-42cd-4caa-9e17-bb4d6596bd41/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/72dcdb89-42cd-4caa-9e17-bb4d6596bd41/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/72dcdb89-42cd-4caa-9e17-bb4d6596bd41/call-hello/execution/rc
