#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/115dffb5-d020-4e41-9cd2-93b98896e8cf/call-hello/execution
echo 'Hello ZXGPSWYVRI!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/115dffb5-d020-4e41-9cd2-93b98896e8cf/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/115dffb5-d020-4e41-9cd2-93b98896e8cf/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/115dffb5-d020-4e41-9cd2-93b98896e8cf/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/115dffb5-d020-4e41-9cd2-93b98896e8cf/call-hello/execution/rc
