#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/23f521df-e016-43fe-b46d-78e06de05441/call-hello/execution
echo 'Hello HXUKPFDZEB!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/23f521df-e016-43fe-b46d-78e06de05441/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/23f521df-e016-43fe-b46d-78e06de05441/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/23f521df-e016-43fe-b46d-78e06de05441/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/23f521df-e016-43fe-b46d-78e06de05441/call-hello/execution/rc
