#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e4127cb2-bc52-4286-85b5-46a7bf994316/call-hello/execution
echo 'Hello KODNWXEJTQ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e4127cb2-bc52-4286-85b5-46a7bf994316/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e4127cb2-bc52-4286-85b5-46a7bf994316/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e4127cb2-bc52-4286-85b5-46a7bf994316/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e4127cb2-bc52-4286-85b5-46a7bf994316/call-hello/execution/rc
