#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/359afbb1-cf21-4ba2-9010-bdaa48b99623/call-hello/execution
echo 'Hello XRLOKCMPZW!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/359afbb1-cf21-4ba2-9010-bdaa48b99623/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/359afbb1-cf21-4ba2-9010-bdaa48b99623/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/359afbb1-cf21-4ba2-9010-bdaa48b99623/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/359afbb1-cf21-4ba2-9010-bdaa48b99623/call-hello/execution/rc
