#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e8d92e13-cc98-41c1-a337-da01979b61da/call-hello/execution
echo 'Hello CVHQUSXRNK!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e8d92e13-cc98-41c1-a337-da01979b61da/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e8d92e13-cc98-41c1-a337-da01979b61da/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e8d92e13-cc98-41c1-a337-da01979b61da/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/e8d92e13-cc98-41c1-a337-da01979b61da/call-hello/execution/rc
