#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/6aebd205-94db-476d-b9b6-22b8c642e8f3/call-hello/execution
echo 'Hello RSPCBLADUO!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/6aebd205-94db-476d-b9b6-22b8c642e8f3/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/6aebd205-94db-476d-b9b6-22b8c642e8f3/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/6aebd205-94db-476d-b9b6-22b8c642e8f3/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/6aebd205-94db-476d-b9b6-22b8c642e8f3/call-hello/execution/rc
