#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0c86eb2b-d0fc-4c81-a1e9-79985a8efc91/call-hello/execution
echo 'Hello DRZTGIEVHL!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0c86eb2b-d0fc-4c81-a1e9-79985a8efc91/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0c86eb2b-d0fc-4c81-a1e9-79985a8efc91/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0c86eb2b-d0fc-4c81-a1e9-79985a8efc91/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0c86eb2b-d0fc-4c81-a1e9-79985a8efc91/call-hello/execution/rc
