#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/39e75e73-94ed-4d36-8197-17d434e4aac3/call-hello/execution
echo 'Hello CTZAHGKYEB!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/39e75e73-94ed-4d36-8197-17d434e4aac3/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/39e75e73-94ed-4d36-8197-17d434e4aac3/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/39e75e73-94ed-4d36-8197-17d434e4aac3/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/39e75e73-94ed-4d36-8197-17d434e4aac3/call-hello/execution/rc
