#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0440e5f6-9418-4abf-b5da-00484f36ae1b/call-hello/execution
echo 'Hello WGQBVFLXAT!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0440e5f6-9418-4abf-b5da-00484f36ae1b/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0440e5f6-9418-4abf-b5da-00484f36ae1b/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0440e5f6-9418-4abf-b5da-00484f36ae1b/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/0440e5f6-9418-4abf-b5da-00484f36ae1b/call-hello/execution/rc
