#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c50d53a0-a973-4a5c-9454-ffe4f83d9e89/call-hello/execution
echo 'Hello CWFYHJSQRX!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c50d53a0-a973-4a5c-9454-ffe4f83d9e89/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c50d53a0-a973-4a5c-9454-ffe4f83d9e89/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c50d53a0-a973-4a5c-9454-ffe4f83d9e89/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/c50d53a0-a973-4a5c-9454-ffe4f83d9e89/call-hello/execution/rc
