#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a26c7cf1-0f34-4d9c-8539-bdfb10bc681e/call-hello/execution
echo 'Hello BLDVJNXTRK!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a26c7cf1-0f34-4d9c-8539-bdfb10bc681e/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a26c7cf1-0f34-4d9c-8539-bdfb10bc681e/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a26c7cf1-0f34-4d9c-8539-bdfb10bc681e/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a26c7cf1-0f34-4d9c-8539-bdfb10bc681e/call-hello/execution/rc
