#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/cee22380-1c77-46ff-ab5b-b9bdd9ab9a66/call-hello/execution
echo 'Hello LRUIVXTWCQ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/cee22380-1c77-46ff-ab5b-b9bdd9ab9a66/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/cee22380-1c77-46ff-ab5b-b9bdd9ab9a66/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/cee22380-1c77-46ff-ab5b-b9bdd9ab9a66/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/cee22380-1c77-46ff-ab5b-b9bdd9ab9a66/call-hello/execution/rc
