#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/120499ae-c9c3-4597-b723-39c07865ec04/call-hello/execution
echo 'Hello WHPYDROMVQ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/120499ae-c9c3-4597-b723-39c07865ec04/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/120499ae-c9c3-4597-b723-39c07865ec04/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/120499ae-c9c3-4597-b723-39c07865ec04/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/120499ae-c9c3-4597-b723-39c07865ec04/call-hello/execution/rc
