#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9a30592-3fa6-4b00-bd34-86a618db5d06/call-hello/execution
echo 'Hello UMRCWEIGLH!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9a30592-3fa6-4b00-bd34-86a618db5d06/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9a30592-3fa6-4b00-bd34-86a618db5d06/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9a30592-3fa6-4b00-bd34-86a618db5d06/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/a9a30592-3fa6-4b00-bd34-86a618db5d06/call-hello/execution/rc
