#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/9885f22b-5dc5-46f7-97d9-06b0f2a85c18/call-hello/execution
echo 'Hello JITDGHBLXE!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/9885f22b-5dc5-46f7-97d9-06b0f2a85c18/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/9885f22b-5dc5-46f7-97d9-06b0f2a85c18/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/9885f22b-5dc5-46f7-97d9-06b0f2a85c18/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/9885f22b-5dc5-46f7-97d9-06b0f2a85c18/call-hello/execution/rc
