#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5ea3574c-7295-486a-a829-256d53defcc7/call-hello/execution
echo 'Hello KABQXYUHEI!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5ea3574c-7295-486a-a829-256d53defcc7/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5ea3574c-7295-486a-a829-256d53defcc7/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5ea3574c-7295-486a-a829-256d53defcc7/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/5ea3574c-7295-486a-a829-256d53defcc7/call-hello/execution/rc
