#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/69f16fdd-91da-4e5e-b49e-564e61a08dcb/call-hello/execution
echo 'Hello PRLAYNVTFZ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/69f16fdd-91da-4e5e-b49e-564e61a08dcb/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/69f16fdd-91da-4e5e-b49e-564e61a08dcb/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/69f16fdd-91da-4e5e-b49e-564e61a08dcb/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/69f16fdd-91da-4e5e-b49e-564e61a08dcb/call-hello/execution/rc
