#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ab70174c-2add-4503-9408-712d56b4d442/call-hello/execution
echo 'Hello FGRJMPLIBX!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ab70174c-2add-4503-9408-712d56b4d442/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ab70174c-2add-4503-9408-712d56b4d442/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ab70174c-2add-4503-9408-712d56b4d442/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/ab70174c-2add-4503-9408-712d56b4d442/call-hello/execution/rc
