#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/7de9be19-8272-459c-98cf-b5604d6a8539/call-hello/execution
echo 'Hello SBMERNHLUQ!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/7de9be19-8272-459c-98cf-b5604d6a8539/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/7de9be19-8272-459c-98cf-b5604d6a8539/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/7de9be19-8272-459c-98cf-b5604d6a8539/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/7de9be19-8272-459c-98cf-b5604d6a8539/call-hello/execution/rc
