#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/60bec49a-622c-4ac4-a933-5eedbcd0ec30/call-hello/execution
echo 'Hello UYOMVTWFJP!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/60bec49a-622c-4ac4-a933-5eedbcd0ec30/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/60bec49a-622c-4ac4-a933-5eedbcd0ec30/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/60bec49a-622c-4ac4-a933-5eedbcd0ec30/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/60bec49a-622c-4ac4-a933-5eedbcd0ec30/call-hello/execution/rc
