#!/bin/sh
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1ca774fd-8e73-4fcb-9ace-cdb1577f3cd4/call-hello/execution
echo 'Hello XMQUAIKVOT!'
)
echo $? > /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1ca774fd-8e73-4fcb-9ace-cdb1577f3cd4/call-hello/execution/rc.tmp
(
cd /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1ca774fd-8e73-4fcb-9ace-cdb1577f3cd4/call-hello/execution

)
mv /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1ca774fd-8e73-4fcb-9ace-cdb1577f3cd4/call-hello/execution/rc.tmp /Users/sdavis2/Documents/git/cRomwell/tests/testthat/cromwell-executions/test/1ca774fd-8e73-4fcb-9ace-cdb1577f3cd4/call-hello/execution/rc
